package com.example.shopapp.domain.filters

data class SearchBarState (
    val categories: List<FilterCategory> = listOf(
        FilterCategory("Акустические гитары"),
        FilterCategory("Классическая гитара"),
        FilterCategory("Электрогитары"),
        FilterCategory("Басс-гитара"),
    ),
    val brands: List<FilterCategory> = listOf(
        FilterCategory("Prima"),
        FilterCategory("Yamaha"),
        FilterCategory("Crafter"),
        FilterCategory("EnyaGuitars"),
        FilterCategory("Framus"),
        FilterCategory("Ovation"),
        FilterCategory("Cort"),
        FilterCategory("Fender"),
        FilterCategory("LAG"),
        FilterCategory("Ortega"),
        FilterCategory("Kremona"),
        FilterCategory("GEWA"),
        FilterCategory("Django"),
        FilterCategory("Alhambra"),
        FilterCategory("Tokai"),
        FilterCategory("Vintage"),
        FilterCategory("Inspector"),
        FilterCategory("DBZ"),
        FilterCategory("Squier"),
        FilterCategory("Ibanez"),
        FilterCategory("FGN"),
        FilterCategory("PRS"),
        FilterCategory("Mayones"),
        FilterCategory("Angelico"),
        FilterCategory("Fernandes"),
    ),
    val colors: List<FilterCategory> = listOf(
        FilterCategory("Натуральный"),
        FilterCategory("Чёрный"),
        FilterCategory("Burst"),
        FilterCategory("Коричневый"),
        FilterCategory("Белый"),
        FilterCategory("Серебряный"),
        FilterCategory("Красный"),
        FilterCategory("Черный"),
        FilterCategory("Серый"),
        FilterCategory("Голубой"),
        FilterCategory("Синий"),
        FilterCategory("Оранжевый"),
        FilterCategory("Розовый"),
        FilterCategory("Перламутр"),
        FilterCategory("Желтый"),
        FilterCategory("Зелёный"),
    ),
    val manufacturer: List<FilterCategory> = listOf(
        FilterCategory("Китай"),
        FilterCategory("Индонезия"),
        FilterCategory("Болгария"),
        FilterCategory("Румыния"),
        FilterCategory("Испания"),
        FilterCategory("Россия"),
        FilterCategory("Корея"),
        FilterCategory("Япония"),
        FilterCategory("Мексика"),
        FilterCategory("Польша"),
        FilterCategory("США"),
    ),
    val material: List<FilterCategory> = listOf(
        FilterCategory("Махагон"),
        FilterCategory("Красное дерево"),
        FilterCategory("Хая"),
        FilterCategory("Нато"),
        FilterCategory("Самангуила"),
        FilterCategory("Клён"),
        FilterCategory("Кедр"),
        FilterCategory("Венге"),
        FilterCategory("Составной"),
    )
)
