package com.example.shopapp.domain.filters

data class SearchBarState (
    val acoustic: Category = Category.Acoustic,
    val classic: Category = Category.Classic,
    val electro: Category = Category.Electro,
    val bass: Category = Category.Bass,

    val prima: Brand = Brand.Prima,
    val yamaha: Brand = Brand.Yamaha,
    val crafter: Brand = Brand.Crafter,
    val enyaGuitars: Brand = Brand.EnyaGuitars,
    val framus: Brand = Brand.Framus,
    val ovation: Brand = Brand.Ovation,
    val cort: Brand = Brand.Cort,
    val fender: Brand = Brand.Fender,
    val lAG: Brand = Brand.LAG,
    val ortega: Brand = Brand.Ortega,
    val kremona: Brand = Brand.Kremona,
    val GEWA: Brand = Brand.GEWA,
    val django: Brand = Brand.Django,
    val alhambra: Brand = Brand.Alhambra,
    val tokai: Brand = Brand.Tokai,
    val vintage: Brand = Brand.Vintage,
    val inspector: Brand = Brand.Inspector,
    val DBZ: Brand = Brand.DBZ,
    val squier: Brand = Brand.Squier,
    val ibanez: Brand = Brand.Ibanez,
    val FGN: Brand = Brand.FGN,
    val PRS: Brand = Brand.PRS,
    val mayones: Brand = Brand.Mayones,
    val angelico: Brand = Brand.Angelico,
    val fernandes: Brand = Brand.Fernandes,

    val china: Manufacturer = Manufacturer.China,
    val indonesia: Manufacturer = Manufacturer.Indonesia,
    val bulgaria: Manufacturer = Manufacturer.Bulgaria,
    val romania: Manufacturer = Manufacturer.Romania,
    val spain: Manufacturer = Manufacturer.Spain,
    val russia: Manufacturer = Manufacturer.Russia,
    val korea: Manufacturer = Manufacturer.Korea,
    val japan: Manufacturer = Manufacturer.Japan,
    val mexico: Manufacturer = Manufacturer.Mexico,
    val poland: Manufacturer = Manufacturer.Poland,
    val USA: Manufacturer = Manufacturer.USA,

    val natural: Color = Color.Natural,
    val black: Color = Color.Black,
    val burst: Color = Color.Burst,
    val brown: Color = Color.Brown,
    val white: Color = Color.White,
    val silver: Color = Color.Silver,
    val red: Color = Color.Red,
    val blackE: Color = Color.BlackE,
    val grey: Color = Color.Grey,
    val blue: Color = Color.Blue,
    val darkBlue: Color = Color.DarkBlue,
    val orange: Color = Color.Orange,
    val pink: Color = Color.Pink,
    val nacre: Color = Color.Nacre,
    val yellow: Color = Color.Yellow,
    val green: Color = Color.Green,
)
